source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TXViewKeyboardResizer_Example', :exclusive => true do
  pod "TXViewKeyboardResizer", :path => "../"
end

target 'TXViewKeyboardResizer_Tests', :exclusive => true do
  pod "TXViewKeyboardResizer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
